CREATE TABLE userin (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(50) NOT NULL unique ,
    username VARCHAR(50) NOT NULL unique,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE session (
    id text PRIMARY KEY,
    expires_at TIMESTAMP NOT NULL
);